[2016-09-30 00:00:08,285] WARNING % : Not Found: /
[2016-09-30 00:00:09,125] WARNING % : Not Found: /favicon.ico
[2016-09-30 00:46:15,648] WARNING % : Not Found: /site/css/style.css
[2016-09-30 00:46:16,945] WARNING % : Not Found: /site/img/favicon.ico
[2016-09-30 00:49:47,886] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:10:52,087] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:10:52,761] WARNING % : Not Found: /site/img/favicon.ico
[2016-10-01 20:10:53,208] WARNING % : Not Found: /site/img/favicon.ico
[2016-10-01 20:10:57,091] WARNING % : Not Found: /accounts/login/
[2016-10-01 20:10:59,939] WARNING % : Not Found: /1/site/css/style.css
[2016-10-01 20:11:00,368] WARNING % : Not Found: /1/site/img/favicon.ico
[2016-10-01 20:11:00,459] WARNING % : Not Found: /1/site/img/favicon.ico
[2016-10-01 20:16:02,559] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:24:58,405] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:26:58,211] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:26:58,766] WARNING % : Not Found: /delivrem/2016/10/01/image_bfiE4Pf.jpg
[2016-10-01 20:26:58,822] WARNING % : Not Found: /delivrem/2016/10/01/image_FVFyRJf.jpg
[2016-10-01 20:26:58,834] WARNING % : Not Found: /delivrem/2016/10/01/image_hpzyXCG.jpg
[2016-10-01 20:26:58,930] WARNING % : Not Found: /delivrem/2016/10/01/image_De2gCZh.jpg
[2016-10-01 20:26:59,017] WARNING % : Not Found: /delivrem/2016/10/01/image_UEtLhSa.jpg
[2016-10-01 20:26:59,185] WARNING % : Not Found: /delivrem/2016/10/01/image_tQop7hW.jpg
[2016-10-01 20:26:59,449] WARNING % : Not Found: /delivrem/2016/10/01/image_b0Avh4g.jpg
[2016-10-01 20:26:59,564] WARNING % : Not Found: /delivrem/2016/10/01/image_Tg7JiLF.jpg
[2016-10-01 20:26:59,708] WARNING % : Not Found: /delivrem/2016/10/01/image_kMR34C5.jpg
[2016-10-01 20:26:59,783] WARNING % : Not Found: /delivrem/2016/10/01/image_zvpsnns.jpg
[2016-10-01 20:27:10,259] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:27:26,571] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:27:40,942] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:29:35,808] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 1402, in get_library
    ','.join(tried_modules)))
django.template.base.InvalidTemplateLibrary: Template library crispy_forms_tags not found, tried django.templatetags.crispy_forms_tags,django.contrib.admin.templatetags.crispy_forms_tags,django.contrib.staticfiles.templatetags.crispy_forms_tags,django.contrib.humanize.templatetags.crispy_forms_tags,django_extensions.templatetags.crispy_forms_tags,debug_toolbar.templatetags.crispy_forms_tags,rest_framework.templatetags.crispy_forms_tags,bootstrap_pagination.templatetags.crispy_forms_tags

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
django.template.base.TemplateSyntaxError: 'crispy_forms_tags' is not a valid tag library: Template library crispy_forms_tags not found, tried django.templatetags.crispy_forms_tags,django.contrib.admin.templatetags.crispy_forms_tags,django.contrib.staticfiles.templatetags.crispy_forms_tags,django.contrib.humanize.templatetags.crispy_forms_tags,django_extensions.templatetags.crispy_forms_tags,debug_toolbar.templatetags.crispy_forms_tags,rest_framework.templatetags.crispy_forms_tags,bootstrap_pagination.templatetags.crispy_forms_tags
[2016-10-01 20:31:17,932] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 1402, in get_library
    ','.join(tried_modules)))
django.template.base.InvalidTemplateLibrary: Template library crispy_forms_tag not found, tried django.templatetags.crispy_forms_tag,django.contrib.admin.templatetags.crispy_forms_tag,django.contrib.staticfiles.templatetags.crispy_forms_tag,django.contrib.humanize.templatetags.crispy_forms_tag,django_extensions.templatetags.crispy_forms_tag,debug_toolbar.templatetags.crispy_forms_tag,rest_framework.templatetags.crispy_forms_tag,bootstrap_pagination.templatetags.crispy_forms_tag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
django.template.base.TemplateSyntaxError: 'crispy_forms_tag' is not a valid tag library: Template library crispy_forms_tag not found, tried django.templatetags.crispy_forms_tag,django.contrib.admin.templatetags.crispy_forms_tag,django.contrib.staticfiles.templatetags.crispy_forms_tag,django.contrib.humanize.templatetags.crispy_forms_tag,django_extensions.templatetags.crispy_forms_tag,debug_toolbar.templatetags.crispy_forms_tag,rest_framework.templatetags.crispy_forms_tag,bootstrap_pagination.templatetags.crispy_forms_tag
[2016-10-01 20:31:21,122] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1159, in load
    lib = get_library(taglib)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 1402, in get_library
    ','.join(tried_modules)))
django.template.base.InvalidTemplateLibrary: Template library crispy_forms_tag not found, tried django.templatetags.crispy_forms_tag,django.contrib.admin.templatetags.crispy_forms_tag,django.contrib.staticfiles.templatetags.crispy_forms_tag,django.contrib.humanize.templatetags.crispy_forms_tag,django_extensions.templatetags.crispy_forms_tag,debug_toolbar.templatetags.crispy_forms_tag,rest_framework.templatetags.crispy_forms_tag,bootstrap_pagination.templatetags.crispy_forms_tag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
django.template.base.TemplateSyntaxError: 'crispy_forms_tag' is not a valid tag library: Template library crispy_forms_tag not found, tried django.templatetags.crispy_forms_tag,django.contrib.admin.templatetags.crispy_forms_tag,django.contrib.staticfiles.templatetags.crispy_forms_tag,django.contrib.humanize.templatetags.crispy_forms_tag,django_extensions.templatetags.crispy_forms_tag,debug_toolbar.templatetags.crispy_forms_tag,rest_framework.templatetags.crispy_forms_tag,bootstrap_pagination.templatetags.crispy_forms_tag
[2016-10-01 20:31:35,545] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 338, in parse
    compile_func = self.tags[command]
KeyError: 'crispy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'crispy', expected 'endblock'
[2016-10-01 20:33:21,299] WARNING % : Not Found: /create/site/css/style.css
[2016-10-01 20:33:21,463] WARNING % : Not Found: /create/site/img/favicon.ico
[2016-10-01 20:35:09,284] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 215, in post
    return self.form_valid(form)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\views.py", line 73, in form_valid
    self.object.author = self.request.user
  File "C:\Users\English\Miniconda3\lib\site-packages\django\db\models\fields\related.py", line 639, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000050C4C50>>": "Product.author" must be a "User" instance.
[2016-10-01 20:36:21,223] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:36:25,853] WARNING % : Not Found: /create/site/css/style.css
[2016-10-01 20:36:37,431] ERROR % : Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 215, in post
    return self.form_valid(form)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\views.py", line 75, in form_valid
    return super(self.__class__, self).form_valid(form)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\views.py", line 46, in form_valid
    messages.success(self.request, self.success_message)
AttributeError: 'ProductCreateView' object has no attribute 'success_message'
[2016-10-01 20:44:17,426] WARNING % : Not Found: /11/site/css/style.css
[2016-10-01 20:44:17,875] WARNING % : Not Found: /11/site/img/favicon.ico
[2016-10-01 20:44:22,147] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:47:45,508] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:48:21,397] WARNING % : Not Found: /update/11/site/css/style.css
[2016-10-01 20:48:21,817] WARNING % : Not Found: /update/11/site/img/favicon.ico
[2016-10-01 20:51:42,049] ERROR % : Internal Server Error: /update/11/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\decorators.py", line 13, in wrap
    return view_fn(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\views.py", line 103, in dispatch
    return super(self.__class__, self).dispatch(self.request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\forms.py", line 84, in __init__
    super(ProductForm, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
[2016-10-01 20:52:07,306] ERROR % : Internal Server Error: /update/11/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\decorators.py", line 13, in wrap
    return view_fn(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\views.py", line 103, in dispatch
    return super(self.__class__, self).dispatch(self.request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "C:\Users\English\Documents\GitHub\wadiyabi\applications\delivrem\forms.py", line 70, in __init__
    super(ProductForm, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
[2016-10-01 20:52:17,734] WARNING % : Not Found: /update/11/site/css/style.css
[2016-10-01 20:52:29,073] WARNING % : Not Found: /11/site/css/style.css
[2016-10-01 20:52:35,429] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:53:15,930] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:54:00,988] WARNING % : Not Found: /update/5/site/css/style.css
[2016-10-01 20:54:01,103] WARNING % : Not Found: /update/5/site/img/favicon.ico
[2016-10-01 20:54:08,850] WARNING % : Not Found: /create/site/css/style.css
[2016-10-01 20:54:22,275] ERROR % : Internal Server Error: /delete/1/
Traceback (most recent call last):
  File "C:\Users\English\Miniconda3\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "C:\Users\English\Miniconda3\lib\site-packages\django\template\loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
django.template.base.TemplateDoesNotExist: _delete_confirm.html
[2016-10-01 20:56:07,369] WARNING % : Not Found: /delete/1/site/css/style.css
[2016-10-01 20:56:07,500] WARNING % : Not Found: /delete/1/site/img/favicon.ico
[2016-10-01 20:56:09,146] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:56:20,774] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:56:23,872] WARNING % : Not Found: /delete/4/site/css/style.css
[2016-10-01 20:56:24,797] WARNING % : Not Found: /delete/4/site/img/favicon.ico
[2016-10-01 20:56:26,100] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:56:31,748] WARNING % : Not Found: /delete/4/site/css/style.css
[2016-10-01 20:56:33,890] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:56:37,032] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:57:14,588] WARNING % : Not Found: /delete/6/site/css/style.css
[2016-10-01 20:57:14,836] WARNING % : Not Found: /delete/6/site/img/favicon.ico
[2016-10-01 20:57:16,169] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:57:19,598] WARNING % : Not Found: /delete/8/site/css/style.css
[2016-10-01 20:57:19,913] WARNING % : Not Found: /delete/8/site/img/favicon.ico
[2016-10-01 20:57:20,015] WARNING % : Not Found: /delete/8/site/img/favicon.ico
[2016-10-01 20:57:21,589] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:58:44,447] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:58:47,301] WARNING % : Not Found: /delete/11/site/css/style.css
[2016-10-01 20:58:47,442] WARNING % : Not Found: /delete/11/site/img/favicon.ico
[2016-10-01 20:58:48,870] WARNING % : Not Found: /site/css/style.css
[2016-10-01 20:58:50,463] WARNING % : Not Found: /delete/11/site/css/style.css
[2016-10-01 20:58:51,920] WARNING % : Not Found: /site/css/style.css
[2016-10-01 21:00:55,940] WARNING % : Not Found: /site/css/style.css
[2016-10-01 21:00:57,573] WARNING % : Not Found: /delete/11/site/css/style.css
[2016-10-01 21:00:59,305] WARNING % : Not Found: /site/css/style.css
[2016-10-01 21:01:42,660] WARNING % : Not Found: /update/10/site/css/style.css
[2016-10-01 21:01:42,895] WARNING % : Not Found: /update/10/site/img/favicon.ico
[2016-10-01 21:05:42,306] WARNING % : Not Found: /site/css/style.css
[2016-10-01 21:08:11,009] WARNING % : Not Found: /site/css/style.css
